import { describe, expect, it } from 'vitest';
import { parseFilter, serializeFilter } from './index';

const INPUTS: string[] = [
  '',
  'order:priority',
  'team:ENG',
  'team:eng',
  'team in:ENG,WEB',
  'team nin:ENG',
  'status:"In Progress"',
  'status neq:Done',
  'status in:"In Progress",Todo,"Won\'t do"',
  'statusCategory:in_progress',
  'statusCategory nin:done,canceled',
  'assignee:me',
  'assignee:empty',
  'assignee neq:me',
  'assignee in:me,alice,empty',
  'assignee:"me"',
  'assignee:john.doe@example.com',
  'creator:bob',
  'creator nin:me',
  'priority:2',
  'priority:urgent',
  'priority lt:2',
  'priority lte:no_priority',
  'priority gt:0',
  'priority gte:3',
  'priority in:0,1,2',
  'priority nin:4',
  'label:bug',
  'label:empty',
  'label nin:bug,"help wanted"',
  'project:Apollo',
  'project:"Project X"',
  'project neq:empty',
  'cycle:current',
  'cycle:empty',
  'cycle in:next,previous',
  'cycle:"Sprint 5"',
  'estimate:5',
  'estimate gte:3',
  'estimate:empty',
  'estimate in:1,2,3,5,8',
  'createdAt gt:-2w',
  'createdAt lt:2026-01-31',
  'createdAt gte:2026-01-31T10:00:00Z',
  'updated gt:-7d',
  'updatedAt lte:+3d',
  'updatedAt gt:-P2W',
  'completedAt:empty',
  'completedAt neq:empty',
  'completed gt:-1m',
  'completedAt lt:-1y',
  'title contains:"login bug"',
  'title startsWith:Fix',
  'title endsWith:"!"',
  'title neq:"a \\"quoted\\" word"',
  'description contains:crash',
  'description:"back\\\\slash"',
  'identifier:ENG-123',
  'identifier:eng-9',
  'identifier in:ENG-1,WEB-2',
  'parent:empty',
  'parent neq:empty',
  'parent:ENG-4',
  'relations:blocks',
  'relations neq:related',
  'relations:empty',
  'is:blocked',
  'not is:blocking',
  'is:duplicate team:ENG',
  'team:A team:B',
  'team:A and team:B and team:C',
  'team:A or team:B',
  'team:A or team:B or team:C',
  'team:A and team:B or team:C and team:D',
  '(team:A or team:B) and team:C',
  'team:A and (team:B or team:C)',
  'not team:A',
  'not not team:A',
  'not (team:A or team:B)',
  'not (team:A and not team:B)',
  '((team:A or team:B) and (team:C or not team:D)) or team:E',
  'not team:A and not team:B',
  'team:A and not (team:B or (team:C and team:D))',
  'assignee:me and statusCategory:in_progress and priority lt:2 and not label:bug order:priority asc',
  'team:ENG order:createdAt desc',
  'team:ENG order:priority asc, createdAt desc, title',
  'order:manual',
  'order:created, updated asc',
  'title:"a and b or c"',
  'title:"(parens)"',
  'title:"colon: and, comma"',
  'label:"empty"',
  'label:"ME"',
  'label:""',
  'label in:"x y",z',
  'IDENTIFIER:eng-1 AND NOT Priority LT:High',
  '  team:A   \n  team:B  ',
  'createdAt gt:2026-01-31T10:00:00+02:00 team:A',
  'label:über',
];

describe('roundtrip', () => {
  it('has at least 60 inputs', () => {
    expect(INPUTS.length).toBeGreaterThanOrEqual(60);
  });
  for (const input of INPUTS) {
    it(`roundtrips ${JSON.stringify(input)}`, () => {
      const first = parseFilter(input);
      const text = serializeFilter(first);
      expect(parseFilter(text)).toEqual(first);
      // serialization is idempotent
      expect(serializeFilter(parseFilter(text))).toBe(text);
    });
  }
});
