import { adsDark } from './generated/ads-dark';
import { light } from './light';
import { statusPalette, chartPalette } from './palette';
import { space, radius, fontSize, fontFamily, duration, zIndex, layout } from './scales';
import type { ThemeName, ThemeTokens } from './types';
import { STATUS_COLORS } from './types';

export const themes: Record<ThemeName, ThemeTokens> = { light, dark: adsDark };

function themeBlock(name: ThemeName): string {
  const t = themes[name];
  const lines: string[] = [];
  for (const [role, value] of Object.entries(t.color)) lines.push(`  --ds-color-${role}: ${value};`);
  lines.push(`  --ds-shadow-none: none;`);
  lines.push(`  --ds-shadow-card: ${t.shadow.card};`);
  lines.push(`  --ds-shadow-overlay: ${t.shadow.overlay};`);
  for (const c of STATUS_COLORS) {
    const pair = statusPalette[name][c];
    lines.push(`  --ds-status-${c}: ${pair.base};`);
    lines.push(`  --ds-status-${c}-text: ${pair.text};`);
    lines.push(`  --ds-status-${c}-bg: color-mix(in srgb, ${pair.base} 15%, transparent);`);
  }
  chartPalette[name].forEach((c, i) => lines.push(`  --ds-chart-${i + 1}: ${c};`));
  lines.push(`  color-scheme: ${name};`);
  return lines.join('\n');
}

function foundations(): string {
  const lines: string[] = [];
  for (const [k, v] of Object.entries(space)) lines.push(`  --ds-space-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(radius)) lines.push(`  --ds-radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(fontSize)) lines.push(`  --ds-font-size-${k}: ${v};`);
  for (const [k, v] of Object.entries(fontFamily)) lines.push(`  --ds-font-${k}: ${v};`);
  for (const [k, v] of Object.entries(duration)) lines.push(`  --ds-duration-${k}: ${v};`);
  for (const [k, v] of Object.entries(zIndex)) lines.push(`  --ds-z-index-${k}: ${v};`);
  lines.push(`  --ds-layout-sidebar: ${layout.sidebarWidth}px;`);
  lines.push(`  --ds-layout-sidebar-compact: ${layout.sidebarWidthCompact}px;`);
  lines.push(`  --ds-layout-panel: ${layout.panelWidth}px;`);
  lines.push(`  --ds-layout-panel-compact: ${layout.panelWidthCompact}px;`);
  lines.push(`  --ds-layout-header: ${layout.viewHeaderHeight}px;`);
  lines.push(`  --ds-layout-row: ${layout.issueRowHeight}px;`);
  lines.push(`  --ds-layout-table-row: ${layout.tableRowHeight}px;`);
  return lines.join('\n');
}

/**
 * Full token stylesheet. Dark is the default (SPEC §4.5): applies to :root and
 * [data-theme="dark"]; [data-theme="light"] overrides atomically.
 */
export function buildTokensCss(): string {
  return `/* GENERATED by @velocity/tokens — the only place hex values live (SPEC §4.2). */
:root {
${foundations()}
}

:root,
[data-theme='dark'] {
${themeBlock('dark')}
}

[data-theme='light'] {
${themeBlock('light')}
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --ds-duration-100: 0ms;
    --ds-duration-150: 0ms;
    --ds-duration-200: 0ms;
  }
}
`;
}
