import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowsRotate,
  faBan,
  faBars,
  faBell,
  faBolt,
  faBoxArchive,
  faCalendar,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleArrowDown,
  faCircleArrowRight,
  faCircleArrowUp,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleMinus,
  faCodeBranch,
  faComment,
  faCopy,
  faCube,
  faDownload,
  faEllipsis,
  faEye,
  faEyeSlash,
  faFileImport,
  faFilter,
  faGear,
  faGripVertical,
  faHouse,
  faInbox,
  faKey,
  faKeyboard,
  faLayerGroup,
  faLink,
  faList,
  faMagnifyingGlass,
  faMoon,
  faPeopleGroup,
  faPen,
  faPlug,
  faPlus,
  faRightFromBracket,
  faRightLeft,
  faRotate,
  faSitemap,
  faSliders,
  faStar as faStarSolid,
  faSun,
  faTableCellsLarge,
  faTableColumns,
  faTag,
  faTrash,
  faTriangleExclamation,
  faUpRightFromSquare,
  faUpload,
  faUser,
  faUserCheck,
  faUsers,
  faWandMagicSparkles,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import { faStar as faStarRegular } from '@fortawesome/free-regular-svg-icons';

/** Structural subset of Font Awesome's IconDefinition (we only read `icon`). */
export interface IconData {
  icon: readonly [number, number, string[], string, string | string[]];
}

/**
 * Semantic icon mapping (SPEC §4.7). Components reference semantic names only so the
 * underlying icon set can be swapped (e.g. for @atlaskit/icon) in one place.
 */
export const iconMap = {
  inbox: faInbox,
  'my-issues': faUserCheck,
  search: faMagnifyingGlass,
  add: faPlus,
  settings: faGear,
  team: faPeopleGroup,
  active: faBolt,
  cycle: faRotate,
  backlog: faLayerGroup,
  project: faCube,
  view: faTableCellsLarge,
  favorite: faStarRegular,
  'star-filled': faStarSolid,
  'chevron-down': faChevronDown,
  'chevron-right': faChevronRight,
  'chevron-left': faChevronLeft,
  'chevron-up': faChevronUp,
  close: faXmark,
  check: faCheck,
  more: faEllipsis,
  filter: faFilter,
  display: faSliders,
  board: faTableColumns,
  list: faList,
  link: faLink,
  github: faCodeBranch,
  comment: faComment,
  archive: faBoxArchive,
  trash: faTrash,
  copy: faCopy,
  edit: faPen,
  user: faUser,
  users: faUsers,
  label: faTag,
  calendar: faCalendar,
  bell: faBell,
  warning: faTriangleExclamation,
  error: faCircleExclamation,
  info: faCircleInfo,
  success: faCircleCheck,
  keyboard: faKeyboard,
  'arrow-up': faArrowUp,
  'arrow-down': faArrowDown,
  'arrow-left': faArrowLeft,
  'arrow-right': faArrowRight,
  'external-link': faUpRightFromSquare,
  'drag-handle': faGripVertical,
  'sub-issue': faSitemap,
  relation: faRightLeft,
  blocked: faBan,
  sun: faSun,
  moon: faMoon,
  logout: faRightFromBracket,
  key: faKey,
  webhook: faPlug,
  upload: faUpload,
  download: faDownload,
  import: faFileImport,
  chart: faChartLine,
  home: faHouse,
  sparkle: faWandMagicSparkles,
  eye: faEye,
  'eye-slash': faEyeSlash,
  refresh: faArrowsRotate,
  sidebar: faBars,
  // priority glyphs (SPEC §4.7 fixed mapping)
  'priority-urgent': faCircleExclamation,
  'priority-high': faCircleArrowUp,
  'priority-medium': faCircleArrowRight,
  'priority-low': faCircleArrowDown,
  'priority-none': faCircleMinus,
} as const satisfies Record<string, IconData>;

export type IconName = keyof typeof iconMap;
