/**
 * Generates src/generated/ads-dark.ts from the published Atlassian Design System
 * dark theme (@atlaskit/tokens, theme "atlassian-dark"). SPEC §4.3: published ADS
 * dark tokens are the source of truth for dark values; this file is generated,
 * never hand-typed. Light values are binding from SPEC §4.2.2/§4.4 (src/light.ts).
 */
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);

interface RawShadowLayer {
  radius: number;
  spread?: number;
  offset: { x: number; y: number };
  color: string;
  opacity: number;
}
interface RawToken {
  cleanName: string;
  value: string | RawShadowLayer[];
}

/** semantic role (ours) → ADS token name */
const MAP: Record<string, string> = {
  primary: 'color.background.brand.bold',
  'primary-hover': 'color.background.brand.bold.hovered',
  'primary-subtle': 'color.background.selected',
  'primary-subtle-hover': 'color.background.selected.hovered',
  text: 'color.text',
  'text-subtle': 'color.text.subtle',
  'text-subtlest': 'color.text.subtlest',
  'text-disabled': 'color.text.disabled',
  'text-inverse': 'color.text.inverse',
  'text-selected': 'color.text.selected',
  link: 'color.link',
  surface: 'elevation.surface',
  'surface-sunken': 'elevation.surface.sunken',
  'surface-raised': 'elevation.surface.raised',
  'surface-overlay': 'elevation.surface.overlay',
  'surface-hover': 'color.background.neutral.subtle.hovered',
  'surface-pressed': 'color.background.neutral.subtle.pressed',
  border: 'color.border',
  'border-input': 'color.border.input',
  'border-selected': 'color.border.selected',
  focus: 'color.border.focused',
  danger: 'color.background.danger.bold',
  'danger-text': 'color.text.danger',
  'danger-subtle': 'color.background.danger',
  warning: 'color.background.warning.bold',
  'warning-text': 'color.text.warning',
  'warning-subtle': 'color.background.warning',
  success: 'color.background.success.bold',
  'success-text': 'color.text.success',
  'success-subtle': 'color.background.success',
  discovery: 'color.background.discovery.bold',
  'discovery-text': 'color.text.discovery',
  'discovery-subtle': 'color.background.discovery',
  'information-subtle': 'color.background.information',
  blanket: 'color.blanket',
  'input-bg': 'color.background.input',
  neutral: 'color.background.neutral',
  'neutral-hover': 'color.background.neutral.hovered',
  icon: 'color.icon',
  'icon-subtle': 'color.icon.subtle',
};

function shadowToCss(layers: RawShadowLayer[]): string {
  return layers
    .map((l) => {
      const alpha = Math.round(l.opacity * 255)
        .toString(16)
        .padStart(2, '0')
        .toUpperCase();
      const base = l.color.length === 9 ? l.color.slice(0, 7) : l.color;
      const spread = l.spread ? ` ${l.spread}px` : '';
      return `${l.offset.x}px ${l.offset.y}px ${l.radius}px${spread} ${base}${alpha}`;
    })
    .join(', ');
}

const mod = require('@atlaskit/tokens/dist/cjs/artifacts/tokens-raw/atlassian-dark.js') as
  | { default: RawToken[] }
  | RawToken[];
const raw: RawToken[] = Array.isArray(mod) ? mod : mod.default;
const byName = new Map(raw.map((t) => [t.cleanName, t.value]));

const colors: Record<string, string> = {};
for (const [role, adsName] of Object.entries(MAP)) {
  const v = byName.get(adsName);
  if (typeof v !== 'string') throw new Error(`ADS token missing or non-color: ${adsName}`);
  colors[role] = v;
}
const shadowCard = byName.get('elevation.shadow.raised');
const shadowOverlay = byName.get('elevation.shadow.overlay');
if (!Array.isArray(shadowCard) || !Array.isArray(shadowOverlay)) throw new Error('ADS shadow tokens missing');

const pkgVersion = (require('@atlaskit/tokens/package.json') as { version: string }).version;
const out = `// GENERATED by scripts/generate-ads.ts from @atlaskit/tokens@${pkgVersion} (theme: atlassian-dark).
// Do not edit by hand — run \`pnpm --filter @velocity/tokens generate\`.
import type { ThemeTokens } from '../types';

export const adsDark: ThemeTokens = {
  color: ${JSON.stringify(colors, null, 4).replace(/\n}/, '\n  }')},
  shadow: {
    card: ${JSON.stringify(shadowToCss(shadowCard as RawShadowLayer[]))},
    overlay: ${JSON.stringify(shadowToCss(shadowOverlay as RawShadowLayer[]))},
  },
};
`;
const target = fileURLToPath(new URL('../src/generated/ads-dark.ts', import.meta.url));
writeFileSync(target, out);
console.log(`wrote ${target}`);
