import { useState } from 'react';
import { useQuery } from '@apollo/client';
import { Button, ConfirmDialog, EmptyState, InlineMessage, Lozenge, Modal, Radio, RadioGroup, Select, Skeleton, Switch, Table, TextField, Tooltip, useFlags } from '@velocity/ui';
import type { TableColumn } from '@velocity/ui';
import { ApiKeysDocument, CreateApiKeyDocument, RevokeApiKeyDocument } from '@/gql/graphql';
import type { ApiKeysQuery } from '@/gql/graphql';
import { formatDate, formatDateTime, formatRelative } from '@/lib/format';
import { useOptimisticMutation } from '@/lib/mutation';
import { useIsOwner, SettingsPage, SettingsSection } from '../common';
import { m } from '@/i18n';

type Row = ApiKeysQuery['apiKeys'][number];

/** 24 hourly bars; height scales to the busiest hour. Decorative: the tooltip and aria-label carry the numbers. */
function Sparkline({ points }: { points: Row['mutationsPerHour'] }) {
  const t = m.settingsAccount.apiKeys;
  const sorted = [...points].sort((a, b) => Date.parse(a.hour) - Date.parse(b.hour)).slice(-24);
  const total = sorted.reduce((n, p) => n + p.count, 0);
  const last = sorted.length ? (sorted[sorted.length - 1]?.count ?? 0) : 0;
  const max = Math.max(1, ...sorted.map((p) => p.count));
  const w = 3;
  const gap = 1;
  const h = 20;
  const label = total === 0 ? t.mutationsNone : t.mutationsTooltip(total, last);
  return (
    <Tooltip content={label}>
      <span className="inline-flex items-center gap-2" tabIndex={0} aria-label={label}>
        <svg width={sorted.length * (w + gap)} height={h} aria-hidden="true" className="text-fg-subtle">
          {sorted.map((p, i) => {
            const bh = p.count === 0 ? 1 : Math.max(2, Math.round((p.count / max) * h));
            return <rect key={p.hour} x={i * (w + gap)} y={h - bh} width={w} height={bh} rx={1} fill="currentColor" opacity={p.count === 0 ? 0.35 : 1} />;
          })}
        </svg>
        <span className="identifier w-8 text-right">{total}</span>
      </span>
    </Tooltip>
  );
}

function CreateKeyModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const t = m.settingsAccount.apiKeys;
  const [name, setName] = useState('');
  const [scope, setScope] = useState<string>('read');
  const [expiry, setExpiry] = useState('0');
  const [touched, setTouched] = useState(false);
  const [secret, setSecret] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const { showFlag } = useFlags();
  const [create, { loading }] = useOptimisticMutation(CreateApiKeyDocument, {
    optimistic: { serverConfirmed: 'The secret and prefix are generated by the server and returned once.' },
    refetchQueries: [ApiKeysDocument],
    rollback: () => t.createFailed,
    silent: true,
  });

  const reset = () => {
    setName('');
    setScope('read');
    setExpiry('0');
    setTouched(false);
    setSecret(null);
    setError(null);
  };
  const close = () => {
    onClose();
    reset();
  };

  const submit = async () => {
    setTouched(true);
    setError(null);
    if (!name.trim()) return;
    const days = Number(expiry);
    const { data, error: err } = await create({
      name: name.trim(),
      scope: scope === 'write' ? 'write' : 'read',
      expiresInDays: days > 0 ? days : undefined,
    });
    if (err) setError(err.message);
    else if (data) setSecret(data.createApiKey.plaintext);
  };

  const copy = () => void navigator.clipboard?.writeText(secret ?? '').then(() => showFlag({ title: t.copied, severity: 'success' }));

  if (secret) {
    return (
      <Modal
        open={open}
        onClose={close}
        title={t.secretTitle}
        footer={
          <Button variant="primary" onClick={close}>
            {m.common.done}
          </Button>
        }
      >
        <div className="flex flex-col gap-4">
          <InlineMessage appearance="warning">{t.secretWarning}</InlineMessage>
          <div className="flex flex-col gap-1">
            <label htmlFor="api-key-secret" className="text-base font-medium text-fg">
              {t.secretLabel}
            </label>
            <div className="flex gap-2">
              <input
                id="api-key-secret"
                readOnly
                value={secret}
                onFocus={(e) => e.currentTarget.select()}
                className="h-8 min-w-0 flex-1 rounded-sm border border-border-input bg-sunken px-3 font-mono text-base text-fg focus-visible:outline-2 focus-visible:outline-primary"
                data-testid="api-key-secret"
              />
              <Button onClick={copy}>
                {m.common.copy}
              </Button>
            </div>
          </div>
        </div>
      </Modal>
    );
  }

  return (
    <Modal
      open={open}
      onClose={close}
      title={t.createTitle}
      isDirty={name.trim().length > 0}
      onSubmit={() => void submit()}
      footer={
        <>
          <Button onClick={close}>{m.common.cancel}</Button>
          <Button variant="primary" loading={loading} onClick={() => void submit()}>
            {t.createAction}
          </Button>
        </>
      }
    >
      <div className="flex flex-col gap-4">
        {error ? <InlineMessage appearance="error">{error}</InlineMessage> : null}
        <TextField label={t.nameLabel} value={name} onChange={(e) => setName(e.target.value)} placeholder={t.namePlaceholder} error={touched && !name.trim() ? t.nameRequired : null} data-autofocus />
        <div className="flex flex-col gap-2">
          <RadioGroup label={t.scopeLabel} value={scope} onChange={setScope}>
            <Radio value="read" label={<span><span className="font-medium">{t.read}</span> <span className="text-sm text-fg-subtle">{t.readHelp}</span></span>} />
            <Radio value="write" label={<span><span className="font-medium">{t.write}</span> <span className="text-sm text-fg-subtle">{t.writeHelp}</span></span>} />
          </RadioGroup>
        </div>
        <Select
          label={t.expiry}
          value={expiry}
          onChange={(e) => setExpiry(e.target.value)}
          options={[
            { value: '0', label: t.expiryNever },
            { value: '30', label: t.expiry30 },
            { value: '90', label: t.expiry90 },
            { value: '365', label: t.expiry365 },
          ]}
        />
      </div>
    </Modal>
  );
}

export function ApiKeysSettings() {
  const t = m.settingsAccount.apiKeys;
  const isOwner = useIsOwner();
  const { showFlag } = useFlags();
  const [all, setAll] = useState(false);
  const [creating, setCreating] = useState(false);
  const [revoking, setRevoking] = useState<Row | null>(null);
  const showAll = isOwner && all;
  const { data, loading, error } = useQuery(ApiKeysDocument, { variables: { all: showAll } });
  const [revoke, { loading: revokeLoading }] = useOptimisticMutation(RevokeApiKeyDocument, {
    optimistic: () => ({ __typename: 'Mutation' as const, revokeApiKey: true }),
    update: (cache, _res, vars) => {
      cache.evict({ id: cache.identify({ __typename: 'ApiKey', id: vars.id }) });
      cache.gc();
    },
    rollback: () => t.revokeFailed,
  });

  const rows = data?.apiKeys ?? [];
  const columns: TableColumn<Row>[] = [
    { key: 'name', header: t.name, render: (k) => <span className="block max-w-56 truncate font-medium text-fg">{k.name}</span> },
    { key: 'prefix', header: t.prefix, render: (k) => <span className="identifier">{k.prefix}</span> },
    { key: 'scope', header: t.scope, render: (k) => <Lozenge appearance={k.scope === 'write' ? 'inprogress' : 'default'}>{k.scope === 'write' ? t.write : t.read}</Lozenge> },
    ...(showAll ? [{ key: 'owner', header: t.owner, render: (k: Row) => <span className="text-fg-subtle">{k.user?.name ?? '–'}</span> }] : []),
    {
      key: 'created',
      header: t.created,
      render: (k) => (
        <Tooltip content={formatDateTime(k.createdAt)}>
          <span className="text-fg-subtle">{formatDate(k.createdAt)}</span>
        </Tooltip>
      ),
    },
    {
      key: 'lastUsed',
      header: t.lastUsed,
      render: (k) => (
        <Tooltip content={k.lastUsedAt ? formatDateTime(k.lastUsedAt) : m.time.never}>
          <span className="whitespace-nowrap text-fg-subtle">{formatRelative(k.lastUsedAt)}</span>
        </Tooltip>
      ),
    },
    { key: 'mutations', header: t.mutations, render: (k) => <Sparkline points={k.mutationsPerHour} /> },
    {
      key: 'actions',
      header: <span className="sr-only">{m.common.more}</span>,
      align: 'right',
      render: (k) => (
        <Button size="sm" variant="subtle" aria-label={t.revokeLabel(k.name)} onClick={() => setRevoking(k)}>
          {t.revoke}
        </Button>
      ),
    },
  ];

  return (
    <SettingsPage
      title={m.settings.sections.apiKeys}
      description={t.description}
      wide
      testId="settings-api-keys"
      actions={
        <Button variant="primary" onClick={() => setCreating(true)}>
          {t.create}
        </Button>
      }
    >
      <SettingsSection
        title={m.settings.sections.apiKeys}
        actions={isOwner ? <Switch label={t.showAll} checked={all} onChange={setAll} /> : null}
      >
        {loading && !data ? (
          <div className="p-4"><Skeleton height={32} rows={3} /></div>
        ) : error ? (
          <div className="p-4">
            <InlineMessage appearance="error">{t.loadFailed}</InlineMessage>
          </div>
        ) : (
          <Table
            aria-label={t.table}
            columns={columns}
            rows={rows}
            rowKey={(k) => k.id}
            emptyState={<EmptyState icon="key" message={t.empty} action={<Button onClick={() => setCreating(true)}>{t.emptyAction}</Button>} />}
          />
        )}
      </SettingsSection>
      <CreateKeyModal open={creating} onClose={() => setCreating(false)} />
      <ConfirmDialog
        open={revoking !== null}
        onClose={() => setRevoking(null)}
        title={revoking ? t.revokeTitle(revoking.name) : ''}
        description={t.revokeBody}
        confirmLabel={t.revoke}
        cancelLabel={m.common.cancel}
        loading={revokeLoading}
        onConfirm={() => {
          const key = revoking;
          if (!key) return;
          setRevoking(null);
          void revoke({ id: key.id }).then((r) => !r.error && showFlag({ title: t.revoked, severity: 'success' }));
        }}
      />
    </SettingsPage>
  );
}
