import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { lexicographicSortSchema, printSchema } from 'graphql';
import { schema } from '../src/schema';

const out = fileURLToPath(new URL('../schema.graphql', import.meta.url));
writeFileSync(out, `# GENERATED by packages/graphql/scripts/print-schema.ts — do not edit.\n${printSchema(lexicographicSortSchema(schema))}\n`);
console.log(`wrote ${out}`);
