// GENERATED from docs/agents.md by scripts/sync-guide.mjs. Do not edit; edit the markdown and re-run.
export const AGENT_GUIDE: string = [
  "# Velocity for AI agents",
  "",
  "Velocity exposes its issue tracker to agents through an MCP server (streamable HTTP at `<server>/mcp`, or stdio via `npx -y <server>/mcp/client-<hash>.tgz`). Every call runs as the API key's user; every mutation is audit-logged with your MCP session id.",
  "",
  "## Quick start",
  "",
  "1. Call `list_teams` first. It returns team keys (e.g. `ENG`), each team's workflow statuses with categories, member usernames and the workspace label names. You need these to create and update issues.",
  "2. Read before you write: `get_issue`, `search_issues` or `list_issues` before `update_issue`, `set_status` or `add_comment`.",
  "3. Cite identifiers (`ENG-123`) everywhere you can.",
  "",
  "## Client verification checklist",
  "",
  "The repository smoke test (`vitest run apps/server/test/mcp-real-client.test.ts`) exercises the real stdio process and streamable HTTP transport against an isolated local server. Each transport creates an issue, adds a comment, sets a Done status and reads the result back. To check a deployed instance with actual clients:",
  "",
  "- [ ] Create a write-scoped API key in Settings > API keys. Configure Claude Code, Claude Desktop, Codex, Cursor or VS Code with the snippets in Settings > MCP ([setup guide](../apps/mcp/README.md)). Restart the client and confirm it lists the `velocity` tools.",
  "- [ ] In that client, call `list_teams`, then `create_issue`, `add_comment`, `set_status` to a Done status and `get_issue`. Confirm the identifier, comment and Done status in the Velocity UI.",
  "- [ ] For an HTTP MCP client (on by default; `MCP_HTTP_ENABLED=0` disables it), connect to `<server>/mcp` with `X-Api-Key: <write-scoped API key>` or `Authorization: Bearer <key>`. If the operator set `MCP_HTTP_TOKEN`, also send it as the Bearer and keep the key in `X-Api-Key`. Repeat the create, comment, close and read sequence.",
  "- [ ] Check Settings > Audit log for the MCP session and mutations. Revoke any key created solely for verification.",
  "",
  "GitHub App installation and a live PR merge require the instance owner's app credentials and repository installation. The signed-webhook E2E spec covers PR linking and merge auto-close with local payloads; after installation, use a real PR containing `Fixes ENG-123` to verify the repository mapping and UI link.",
  "",
  "## Tools",
  "",
  "| Tool | Inputs | What it does |",
  "|---|---|---|",
  "| `list_teams` | none | Teams, keys, workflow statuses (with categories), member usernames, labels. |",
  "| `create_issue` | `team_key`, `title`, `description?`, `priority?`, `labels?`, `assignee?`, `status?`, `estimate?`, `project_id?`, `cycle_id?`, `parent?` | Creates an issue in the team's default status unless `status` is given. Returns the identifier. |",
  "| `get_issue` | `identifier` (or `id`) | Full detail: description, status, labels, assignee, comments, relations, linked PRs, sub-issues, URL. |",
  "| `search_issues` | `query`, `filter_dsl?`, `limit?` | Full-text search (same engine as the UI). `filter_dsl` narrows the hits. |",
  "| `list_issues` | `team_key?`, `filter_dsl?`, `status?`, `assignee?`, `cursor?`, `limit?` | Pages of 50. Pass `next_cursor` back as `cursor`. `status` and `assignee` are merged into the DSL. |",
  "| `update_issue` | `issue_id` (identifier or UUID), `patch`, `expected_updated_at?` | Patch title, description, priority, estimate, assignee, status, labels (replaces the set), project_id, milestone_id, cycle_id, parent. Use `null` to clear nullable fields. |",
  "| `set_status` | `identifier`, `status_name` | Moves an issue to a workflow status by name (case-insensitive). Errors list the valid names for that team. |",
  "| `assign_issue` | `identifier`, `assignee` (`username`, `\"me\"` or `null`) | Assigns or unassigns. |",
  "| `manage_labels` | `action` (`add`/`remove`), `identifier`, `labels[]` | Adds or removes label names without touching other labels. Unknown names produce an error listing available labels. |",
  "| `add_comment` | `identifier`, `body_md` | Markdown comment as the key's user. |",
  "| `list_cycles` | `team_key`, `limit?` | Active, upcoming and recent cycles with `stats` (closed) and `liveStats` (current). |",
  "| `list_projects` | `status?`, `team_key?` | Projects with status, health and progress. |",
  "| `get_project` | `id` (UUID or exact name) | Project, milestones and progress. |",
  "",
  "Priorities: `0` Urgent, `1` High, `2` Medium, `3` Low, `4` No priority. Anywhere a priority is accepted you can pass the number or its name (`urgent`, `high`, `medium`, `low`, `none`).",
  "",
  "Every tool result has a short text block and a `structuredContent` JSON object. Issue objects always include `identifier`, `status`, `priority`, `assignee`, `labels` and `url`.",
  "",
  "## Identifier syntax",
  "",
  "```",
  "ENG-123                         plain reference (case-insensitive team key)",
  "Fixes ENG-123                   close keyword: Fixes | Closes | Resolves",
  "https://<host>/issue/<uuid>     issue URL (accepted wherever an identifier is)",
  "```",
  "",
  "- Put identifiers in commit messages, branch names and PR descriptions so the GitHub integration links them automatically.",
  "- `Fixes ENG-123` / `Closes ENG-123` / `Resolves ENG-123` in a PR body moves the issue to a done status when the PR merges (if auto-close is enabled). Use a plain `ENG-123` when the PR only relates to the issue.",
  "- Tools accept an identifier or a UUID for issues; always prefer the identifier.",
  "",
  "## Filter DSL cheat sheet",
  "",
  "The `filter_dsl` argument uses the same server-side parser as the web app. Clauses are joined with `and` (implicit), `or`, `not`, and parentheses.",
  "",
  "```",
  "comparison := field[ op]:value        no spaces around \":\"",
  "op         := eq neq gt gte lt lte in nin contains startsWith endsWith",
  "fields     := team status statusCategory assignee creator priority label project cycle",
  "              estimate createdAt updatedAt completedAt title description identifier",
  "              parent relations",
  "order      := order:priority asc, createdAt desc      (must be last)",
  "```",
  "",
  "Examples:",
  "",
  "```",
  "assignee:me and statusCategory:in_progress",
  "status:\"In Progress\" and priority lt:2",
  "priority in:0,1 and not label:bug",
  "label:bug and assignee:empty order:priority asc",
  "title contains:\"login\" and updatedAt gt:-7d",
  "cycle:current and statusCategory:todo",
  "(label:frontend or label:design) and project:\"Website\"",
  "identifier:ENG-123",
  "is:blocked",
  "```",
  "",
  "- `me` is the key's user, `empty` matches \"none\" (`assignee:empty`, `label:empty`).",
  "- Quote values containing spaces: `status:\"In Progress\"`.",
  "- `statusCategory` is one of `backlog`, `todo`, `in_progress`, `done`, `canceled`.",
  "- Dates: `2026-01-31`, or relative like `-7d`, `-2w`, `-1m`.",
  "- A malformed DSL returns a VALIDATION error containing the input with a caret under the offending position. Fix it there and retry; do not guess.",
  "",
  "## Etiquette",
  "",
  "- Call `list_teams` first; do not guess team keys, status names or label names.",
  "- Read before you write. Re-read (`get_issue`) before updating an issue someone else may have changed; use `expected_updated_at` to guard against races.",
  "- Do not spam comments. Batch your findings into one comment instead of many.",
  "- Prefer `set_status` over editing the description to report progress. Keep descriptions for the spec of the work.",
  "- Prefer the narrow tools (`set_status`, `assign_issue`, `manage_labels`) over `update_issue` for single-property changes.",
  "- Cite identifiers (`ENG-123`) in commits, branches and PRs; use `Fixes ENG-123` only when the change completes the issue.",
  "- Search before you create to avoid duplicates.",
  "- Page through `list_issues` with `cursor` instead of requesting everything at once.",
  "- Use read-scoped API keys for read-only agents (triage summaries, reporting). Only give write-scoped keys to agents that must change data.",
  "",
  "## Errors",
  "",
  "Failures come back as tool results with `isError: true` and a message that begins with a code:",
  "",
  "| Code | Meaning | What to do |",
  "|---|---|---|",
  "| `VALIDATION` | Bad input: unknown status or label name, bad DSL, bad field. | Read the message: it lists valid names or shows the DSL caret. Fix and retry. |",
  "| `NOT_FOUND` | Unknown identifier, team key or project. | Check with `search_issues`, `list_issues`, `list_teams`. |",
  "| `FORBIDDEN` | The key cannot do that. Writing with a read-scoped key is the usual cause. | Stop and ask for a write-scoped key; do not retry. |",
  "| `CONFLICT` | The issue changed since `expected_updated_at`. | `get_issue`, merge, retry. |",
  "| `RATE_LIMITED` | Too many requests. | Back off and retry later. |",
  "| `UNAUTHENTICATED` | Missing, invalid or expired API key. | Check `VELOCITY_API_KEY`. |",
].join('\n') + '\n';
